// <auto-generated />
using System;
using AIChaos.Brain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIChaos.Brain.Migrations
{
    [DbContext(typeof(AIChaosDbContext))]
    [Migration("20251214065121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("AIChaos.Brain.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRequestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedYouTubeChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingVerificationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedoCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SessionExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationCodeExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedYouTubeChannelId");

                    b.HasIndex("SessionToken");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AIChaos.Brain.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("AIChaos.Brain.Models.PendingChannelCredits", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.ToTable("PendingCredits");
                });

            modelBuilder.Entity("AIChaos.Brain.Models.AppSettings", b =>
                {
                    b.OwnsOne("AIChaos.Brain.Models.AdminSettings", "Admin", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.GeneralSettings", "General", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("BlockLinksInGeneratedCode")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("StreamMode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.OpenRouterSettings", "OpenRouter", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ApiKey")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("BaseUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.SafetySettings", "Safety", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("AllowedDomains")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("BlockUrls")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("Moderators")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("PrivateDiscordMode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.StreamStateSettings", "StreamState", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LastTwitchChannel")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("LastUpdated")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastYouTubeVideoId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("WasStreamLive")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WasTwitchListening")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WasYouTubeListening")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.TestClientSettings", "TestClient", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CleanupAfterTest")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GmodPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsConnected")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("LastPollTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TestMap")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("TimeoutSeconds")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.TunnelSettings", "Tunnel", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CurrentUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsRunning")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.TwitchSettings", "Twitch", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AccessToken")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ChatCommand")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientSecret")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("CooldownSeconds")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MinBitsAmount")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RefreshToken")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("RequireBits")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.OwnsOne("AIChaos.Brain.Models.YouTubeSettings", "YouTube", b1 =>
                        {
                            b1.Property<int>("AppSettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AccessToken")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AllowRegularChat")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AllowViewerOAuth")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ChatCommand")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientSecret")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("CooldownSeconds")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("MinSuperChatAmount")
                                .HasColumnType("TEXT");

                            b1.Property<int>("PollingIntervalSeconds")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RefreshToken")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("VideoId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AppSettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppSettingsId");
                        });

                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("General")
                        .IsRequired();

                    b.Navigation("OpenRouter")
                        .IsRequired();

                    b.Navigation("Safety")
                        .IsRequired();

                    b.Navigation("StreamState")
                        .IsRequired();

                    b.Navigation("TestClient")
                        .IsRequired();

                    b.Navigation("Tunnel")
                        .IsRequired();

                    b.Navigation("Twitch")
                        .IsRequired();

                    b.Navigation("YouTube")
                        .IsRequired();
                });

            modelBuilder.Entity("AIChaos.Brain.Models.PendingChannelCredits", b =>
                {
                    b.OwnsMany("AIChaos.Brain.Models.DonationRecord", "Donations", b1 =>
                        {
                            b1.Property<string>("PendingChannelCreditsChannelId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Message")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.HasKey("PendingChannelCreditsChannelId", "Id");

                            b1.ToTable("DonationRecords", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PendingChannelCreditsChannelId");
                        });

                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
